### ISSUE TITLE
Monitorhalterungen TV+Bildschirm

### ISSUE THREAD

**Issue by confluencepoint** [confluencepoint/Awesome-iPhoneBlog.de-List#62]
[TV Wandhalterung Fernsehhalterung mit VESA Lift Monitorständer](https://www.monitorhalterung.de/)

**Comment by schwabochino** [comment]
"Premium" Wandhalterung für flache Montage an der Wand [Vogels](https://www.vogels.com/) z. B. [Vogels TVM 5405] ausgelegt für 75 KG (https://www.vogels.com/de-de/c/tvm-5405-flache-tv-wandhalterung) Bestpreis über Preissuche der Wahl
